version: "3.9"
services:
  db:
    container_name: db
    image: postgres:14.3-alpine
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_DB=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    command: -p 5432

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10-management
    ports:
      - "5672:5672"
      - "15672:15672"

  main-dev-container:
    container_name: main-dev-container
    build: .
    volumes:
      - .:/workspace
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq