version: "3.9"
services:

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_DB=gpl_outbound_service_db
      - POSTGRES_PASSWORD=postgresql
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
  sftp:
    image: "emberstack/sftp"
    ports:
        - "10000:22"
    volumes:
      - .local/sftp/sftp-directories.json:/app/config/sftp.json:ro

  main-dev-container:
    container_name: main-dev-container
    build: devcontainer/.
    volumes:
      - .:/workspace
    command: tail -f /dev/null
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - rabbitmq
      - sftp
