version: "3.9"
services:
  test-db:
    container_name: test-db
    image: 'postgres:14.3-alpine'
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_DB=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    command: -p 5432

  test-rabbitmq:
    container_name: test-rabbitmq
    image: rabbitmq:3.10-management
    ports:
      - "5672:5672"
      - "15672:15672"

  myapp:
    container_name: myapp
    build:
      context: .
      dockerfile: Dockerfile