server:
  port: 8081
gpl:
  salesdata:
    countries: MT
  inbound:
    service:
      base-path: http://localhost:8080/api/v1
      trigger:
        cron: "0 0/1 * * * *"
  datasource:
    url: postgresql://developer:postgresql@postgres:5432/gpl_outbound_service_db
  rabbitmq:
    movementdataqueuename: MovementDataQueue
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    schemas: shedlock,outbound_service
    locations: classpath:db/migration
    enabled: true
    encoding: UTF-8
  rabbitmq:
    ssl:
      enabled: false
    addresses: amqp://guest:guest@rabbitmq:5672
sftp:
  remote-directory: "test/movement"
  host: 'sftp'
  port: 10000
  user: 'demo'
  password: 'demo'
  timeout-minutes: 10
logging:
  level:
    org:
      springframework:
        web:
         filter:
           CommonsRequestLoggingFilter: DEBUG
        security:
          oauth2: trace
management:
  endpoint:
    health:
      probes:
        enabled: true
