spring:
  config:
    activate:
      on-profile: default

  datasource:
    url: jdbc:postgresql://postgres:5432/root
    username: root
    password: root

  rabbitmq:
    ssl:
      enabled: false
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
